spring:
  datasource:
    url: jdbc:h2:mem:spreadsheet_brain
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true

  # Neo4j Configuration
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: test12345

# Google Sheets API
google:
  sheets:
    application-name: SuperJoinAI
    credentials-file-path: /Users/kumarpranav/IdeaProjects/SuperJoinAI/superjionai-21ae31e8b966.json

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.superjoin.spreadsheetbrain: DEBUG
    org.neo4j: INFO
